// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArKop46eDQ-qV2szM8aKujPsO8MaFE59c',
    appId: '1:186184635097:web:284ef1d0306f659794e4c8',
    messagingSenderId: '186184635097',
    projectId: 'flutter-app-productes-89fe0',
    authDomain: 'flutter-app-productes-89fe0.firebaseapp.com',
    databaseURL: 'https://flutter-app-productes-89fe0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productes-89fe0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDgScZ6JgP40Y17G3mgnYNhE8BMu_90Pk',
    appId: '1:186184635097:android:a218e006fbe8a26b94e4c8',
    messagingSenderId: '186184635097',
    projectId: 'flutter-app-productes-89fe0',
    databaseURL: 'https://flutter-app-productes-89fe0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productes-89fe0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxEJUtM7kGTMOJeuupb1K_3xuvseftmNo',
    appId: '1:186184635097:ios:b2d14bb6966849fb94e4c8',
    messagingSenderId: '186184635097',
    projectId: 'flutter-app-productes-89fe0',
    databaseURL: 'https://flutter-app-productes-89fe0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productes-89fe0.appspot.com',
    iosBundleId: 'com.example.productesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxEJUtM7kGTMOJeuupb1K_3xuvseftmNo',
    appId: '1:186184635097:ios:b2d14bb6966849fb94e4c8',
    messagingSenderId: '186184635097',
    projectId: 'flutter-app-productes-89fe0',
    databaseURL: 'https://flutter-app-productes-89fe0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productes-89fe0.appspot.com',
    iosBundleId: 'com.example.productesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArKop46eDQ-qV2szM8aKujPsO8MaFE59c',
    appId: '1:186184635097:web:5557d0750e55ddbf94e4c8',
    messagingSenderId: '186184635097',
    projectId: 'flutter-app-productes-89fe0',
    authDomain: 'flutter-app-productes-89fe0.firebaseapp.com',
    databaseURL: 'https://flutter-app-productes-89fe0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productes-89fe0.appspot.com',
  );
}
